travis:
  secure:
    BINSTAR_TOKEN: dHG3PhUcD/o341cOBdVDXf0hmv4EP8JAjUTDBoN5HYYX1YPB7eOW2OUcGptx8vvx4sOhpGN5ptjJWrHy4Ard6uQUiDO93U5x4cYo/S5qayhqQtYopWJEe2bLD2/0c/66KKJeTluU1YoedqkSirJt42byMY9pBLNInH8rqfRrCrWJHwd+uynB2S5pASglSUdbGsdptL5os5Apf3CswqRQOOidaTYZcflWnrghjsvUZfkKx3YX7g2x2qQ6oAP61f8r3FiVxnghxCMSVb/xzOP51qmcQA7T0Y6xLCZolqDTZ2jtHoe3tTChfRyK/EmSU6HVodqz4FPvvEmaLs9kLytcMQTv+ywUTOGRnyYgsrrg4ZxyH/3f44RwZHQkchM2ijkz14vd4PJP0ZIm09O2Rr8DOsIRuQAanofN72gz/rD/lKyZljqRhroxQIFKw87QFX+Sxi5DOYtW66zLkYFwOxkrOxkbxk+RVOfStf6bQkRKatq8FlvYEP5bEzBzWNrunUO8YdihFJTdSpwY3zzmFhpn/GClBlr3k8gOqqIu6RRR3TfF329zzWRtRf2h3isTB/uRjUvIk+b7gn7nXBxUJV7RjXsIojqtZWXbBiBRxJPCzkJ7cadW4t/O4+iZTe8NfmOePNoHvIna2HDATB21z6zDoik6OnCc0Ykv1OuKhbxgI30=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
channels:
  targets:
    - [conda-forge, dev]
